name: Deploy to GitHub Pages

on: 
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js (for build tasks)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      # Install dependencies
      - name: Install dependencies
        run: |
          npm install

      # Build the project (skip CI errors)
      - name: Build project
        run: |
          CI=false npm run build

      # Deploy to GitHub Pages (main branch)
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'  # Only deploy on main branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # The branch where the built files will be deployed
          folder: ./build   # The directory containing the build files (update as necessary)
          token: ${{ secrets.MY_GITHUB_TOKEN }}

      # Deploy to staging (develop branch)
      - name: Deploy to GitHub Pages (Staging)
        if: github.ref == 'refs/heads/develop'  # Only deploy on develop branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # The branch where the built files will be deployed
          folder: ./build   # The directory containing the build files (update as necessary)
          token: ${{ secrets.MY_GITHUB_TOKEN }}
